### ISSUE TITLE
two questions about cartography

### ISSUE THREAD

**Issue by dyh333** [nicoptere/cartography#1]
hi, @nicoptere.  there are two questions about cartography which i like very much. (http://barradeau.com/projects/cartography/habitat/full_city/index.html).
1. can it support loading osm tile map ?
2. the taxi gps data have four fields. the first two fields are lat and lon, what last two fields means? and how to identify which points are from the same car?
thanks very much .

**Comment by nicoptere** [comment]
hi,
thanks for your interset.

1 yes and no, it depends on which tileset you're talking about.
I'm using this tileset:
https://openstreetmap.us/~migurski/vector-datasource/
in my code, that's where I recieve the data:
https://github.com/nicoptere/cartography/blob/master/habitat/full_city/js/map.js#L24-L39
and that's where I parse the JSON to retrieve lat/lons and build the actual geometry:
https://github.com/nicoptere/cartography/blob/master/habitat/full_city/js/builder.js#L20-L81

2 the third is whether or not the cab was empty (0 idle, 1 busy) and the forth is a timestamp.
each file from https://github.com/nicoptere/cartography/tree/master/taxi/cabspottingdata contains the information of a single cab.

hope it helps,
Nicolas

**Comment by dyh333** [comment]
thank for your answer.
