### ISSUE TITLE
a bug about geojson data

### ISSUE THREAD

**Issue by dyh333** [nicoptere/cartography#2]
hi, @nicoptere . i found a little bug when i load a local water geojson file just like you load osm building data at map.js . you know, the lake always has some islands, so that the water geojson may be complex. but at builder.js you seems don't consider the situation? so the result water polygon i drew on map seems not right. 
this is my test water geojson:
var json = {
    "type": "FeatureCollection",
    "features": [
        {
            "type": "Feature",
            "geometry": {
                type: "Polygon",
                "coordinates": [
                    [
                        [
                            120.68635741800006,
                            31.326669202000062
                        ],
                        [
                            120.68599246800011,
                            31.326905466000028
                        ],
                        [
                            120.6853246070001,
                            31.328691780000042
                        ],
                        [
                            120.68453049700008,
                            31.329130404000068
                        ],
                        [
                            120.68450263300008,
                            31.330088139000054
                        ],
                        [
                            120.68450160200007,
                            31.330349693000073
                        ],
                        [
                            120.6839405290001,
                            31.330107749000035
                        ],
                        [
                            120.68352576900008,
                            31.329127250000056
                        ],
                        [
                            120.68236407000006,
                            31.328476528000067
                        ],
                        [
                            120.68173552200005,
                            31.327747033000037
                        ],
                        [
                            120.68113462500003,
                            31.325678813000025
                        ],
                        [
                            120.6795732270001,
                            31.324821258000043
                        ],
                        [
                            120.67832191200011,
                            31.324926083000037
                        ],
                        [
                            120.67886493700007,
                            31.32425375500003
                        ],
                        [
                            120.67829347000009,
                            31.324073800000065
                        ],
                        [
                            120.6786784310001,
                            31.322942744000045
                        ],
                        [
                            120.6784231360001,
                            31.322429974000045
                        ],
                        [
                            120.67773116000001,
                            31.322246818000053
                        ],
                        [
                            120.67707972500011,
                            31.322501637000073
                        ],
                        [
                            120.67677391000007,
                            31.323994879000054
                        ],
                        [
                            120.67615710500002,
                            31.324405222000053
                        ],
                        [
                            120.67672094700004,
                            31.323921730000052
                        ],
                        [
                            120.6768834500001,
                            31.322540528000047
                        ],
                        [
                            120.67760865700006,
                            31.322180299000024
                        ],
                        [
                            120.67856459300003,
                            31.32222792300007
                        ],
                        [
                            120.67890179200003,
                            31.32175374700006
                        ],
                        [
                            120.67906369600007,
                            31.320830296000054
                        ],
                        [
                            120.6779735240001,
                            31.320655801000044
                        ],
                        [
                            120.6781134150001,
                            31.320035634000078
                        ],
                        [
                            120.67762612400008,
                            31.319955952000043
                        ],
                        [
                            120.67778953100003,
                            31.319211755000026
                        ],
                        [
                            120.6783264820001,
                            31.319054649000066
                        ],
                        [
                            120.67842057400003,
                            31.31860024100007
                        ],
                        [
                            120.68123395400005,
                            31.31778752100007
                        ],
                        [
                            120.68097193200003,
                            31.31711974500007
                        ],
                        [
                            120.68015375100003,
                            31.317062871000076
                        ],
                        [
                            120.68028449300004,
                            31.316503024000042
                        ],
                        [
                            120.67986128000007,
                            31.316146527000058
                        ],
                        [
                            120.68069104000006,
                            31.313444111000024
                        ],
                        [
                            120.68080523200001,
                            31.31086004900004
                        ],
                        [
                            120.68053162700005,
                            31.309128024000074
                        ],
                        [
                            120.68005516500011,
                            31.30931215100003
                        ],
                        [
                            120.67988279700012,
                            31.308968427000025
                        ],
                        [
                            120.68016213300007,
                            31.308627743000045
                        ],
                        [
                            120.67964238900004,
                            31.307575155000052
                        ],
                        [
                            120.6797937230001,
                            31.306618452000066
                        ],
                        [
                            120.67875267800002,
                            31.30552679400006
                        ],
                        [
                            120.6788517760001,
                            31.304845777000025
                        ],
                        [
                            120.67946985300011,
                            31.304493567000065
                        ],
                        [
                            120.68159188900006,
                            31.304677405000064
                        ],
                        [
                            120.68138106000004,
                            31.303962240000033
                        ],
                        [
                            120.68011110400005,
                            31.30369939900004
                        ],
                        [
                            120.68013976100008,
                            31.303476717000024
                        ],
                        [
                            120.68089995700007,
                            31.303442317000076
                        ],
                        [
                            120.68100445400012,
                            31.302919691000056
                        ],
                        [
                            120.68114387300011,
                            31.303151263000075
                        ],
                        [
                            120.68284963300005,
                            31.303308344000072
                        ],
                        [
                            120.6842681390001,
                            31.30251241800005
                        ],
                        [
                            120.68454138800007,
                            31.301428216000033
                        ],
                        [
                            120.686284967,
                            31.29897531000006
                        ],
                        [
                            120.68684004400006,
                            31.29870315900007
                        ],
                        [
                            120.68687335400011,
                            31.297952855000062
                        ],
                        [
                            120.68730397800005,
                            31.297936721000042
                        ],
                        [
                            120.68732833900003,
                            31.29859622400005
                        ],
                        [
                            120.68801155400001,
                            31.299032530000034
                        ],
                        [
                            120.68819344200006,
                            31.299661465000042
                        ],
                        [
                            120.68830477000006,
                            31.299416165000025
                        ],
                        [
                            120.68870832700009,
                            31.299846496000043
                        ],
                        [
                            120.68963225000005,
                            31.29949229300007
                        ],
                        [
                            120.69038220100003,
                            31.29971658000005
                        ],
                        [
                            120.69050646400001,
                            31.300459427000078
                        ],
                        [
                            120.69011971600003,
                            31.29980924700004
                        ],
                        [
                            120.68958393100002,
                            31.299723448000066
                        ],
                        [
                            120.68904628400003,
                            31.30031464900003
                        ],
                        [
                            120.68859600000008,
                            31.300370826000062
                        ],
                        [
                            120.68904632500005,
                            31.30035128800006
                        ],
                        [
                            120.68900082800008,
                            31.30075774900007
                        ],
                        [
                            120.68956848300002,
                            31.301157501000034
                        ],
                        [
                            120.6902917650001,
                            31.30100977400008
                        ],
                        [
                            120.69050653200009,
                            31.30051805100004
                        ],
                        [
                            120.69051354200008,
                            31.300909250000075
                        ],
                        [
                            120.69092186600005,
                            31.30089988800006
                        ],
                        [
                            120.6908461380001,
                            31.30127086300007
                        ],
                        [
                            120.69202571200003,
                            31.30172194800008
                        ],
                        [
                            120.6921904730001,
                            31.302273101000026
                        ],
                        [
                            120.69173674800004,
                            31.30276784700004
                        ],
                        [
                            120.6923708380001,
                            31.303824236000025
                        ],
                        [
                            120.6944924610001,
                            31.303650479000055
                        ],
                        [
                            120.69629036600008,
                            31.303978099000062
                        ],
                        [
                            120.69798404400001,
                            31.303886397000042
                        ],
                        [
                            120.69946633600011,
                            31.302740758000027
                        ],
                        [
                            120.70289528100011,
                            31.302293121000048
                        ],
                        [
                            120.70435853000004,
                            31.30142902800003
                        ],
                        [
                            120.70625282500009,
                            31.30143001700003
                        ],
                        [
                            120.70694129000003,
                            31.300782794000042
                        ],
                        [
                            120.70736268600001,
                            31.300848313000074
                        ],
                        [
                            120.70785029000001,
                            31.301857256000062
                        ],
                        [
                            120.70932085400011,
                            31.301978808000058
                        ],
                        [
                            120.70971926900006,
                            31.301563612000052
                        ],
                        [
                            120.71013679500004,
                            31.301562071000035
                        ],
                        [
                            120.71206169800007,
                            31.303536459000043
                        ],
                        [
                            120.71268602900011,
                            31.304011023000044
                        ],
                        [
                            120.71308248300011,
                            31.303954816000044
                        ],
                        [
                            120.71281583500001,
                            31.304832760000068
                        ],
                        [
                            120.71071984600007,
                            31.305509045000065
                        ],
                        [
                            120.710698148,
                            31.306940851000036
                        ],
                        [
                            120.7110680080001,
                            31.307598313000028
                        ],
                        [
                            120.71187501500003,
                            31.30777935800006
                        ],
                        [
                            120.71198287700008,
                            31.30809455800005
                        ],
                        [
                            120.71257241800004,
                            31.30809284600008
                        ],
                        [
                            120.71218729300006,
                            31.308693015000074
                        ],
                        [
                            120.713138017,
                            31.308952774000034
                        ],
                        [
                            120.71218412600001,
                            31.308913328000074
                        ],
                        [
                            120.71252807400003,
                            31.30901992300005
                        ],
                        [
                            120.71244931900003,
                            31.30928153800005
                        ],
                        [
                            120.71152662700001,
                            31.30882727100004
                        ],
                        [
                            120.71063113500009,
                            31.308848460000036
                        ],
                        [
                            120.71052261900002,
                            31.31016986700007
                        ],
                        [
                            120.70988233500009,
                            31.31152562400007
                        ],
                        [
                            120.70986261400003,
                            31.312484487000063
                        ],
                        [
                            120.71029997100004,
                            31.31352068700005
                        ],
                        [
                            120.71159243000011,
                            31.313787185000024
                        ],
                        [
                            120.71282383900007,
                            31.31330730700006
                        ],
                        [
                            120.7133156330001,
                            31.313681829000075
                        ],
                        [
                            120.71676945600007,
                            31.313244647000033
                        ],
                        [
                            120.71805950300006,
                            31.31270383800006
                        ],
                        [
                            120.71921518400006,
                            31.31278773300005
                        ],
                        [
                            120.71916831600004,
                            31.31306850200008
                        ],
                        [
                            120.71679921200007,
                            31.313855661000048
                        ],
                        [
                            120.71507780400009,
                            31.31395158400005
                        ],
                        [
                            120.71357666600011,
                            31.31475356800007
                        ],
                        [
                            120.71157064200008,
                            31.31511467000007
                        ],
                        [
                            120.71138561300006,
                            31.315207866000037
                        ],
                        [
                            120.71197871400011,
                            31.315838606000057
                        ],
                        [
                            120.71101167600011,
                            31.316410035000047
                        ],
                        [
                            120.70828771600009,
                            31.316101007000043
                        ],
                        [
                            120.70728096000005,
                            31.31744470500007
                        ],
                        [
                            120.70639247000008,
                            31.317863825000074
                        ],
                        [
                            120.70407752000006,
                            31.320093752000048
                        ],
                        [
                            120.70361189800008,
                            31.321573887000056
                        ],
                        [
                            120.70433203900006,
                            31.321942989000036
                        ],
                        [
                            120.70415375200002,
                            31.322189491000074
                        ],
                        [
                            120.70342048900011,
                            31.32182941900004
                        ],
                        [
                            120.70208843800003,
                            31.322551065000027
                        ],
                        [
                            120.69978377600012,
                            31.32265747100007
                        ],
                        [
                            120.69843791400001,
                            31.321783277000065
                        ],
                        [
                            120.69702983600007,
                            31.321567517000062
                        ],
                        [
                            120.69639607200008,
                            31.322016216000065
                        ],
                        [
                            120.69612132400005,
                            31.322882856000035
                        ],
                        [
                            120.69625014300004,
                            31.32407438900003
                        ],
                        [
                            120.69699270100011,
                            31.324526939000066
                        ],
                        [
                            120.69687605000001,
                            31.32472038900005
                        ],
                        [
                            120.69589502200006,
                            31.32472745900003
                        ],
                        [
                            120.69474029100002,
                            31.325551464000057
                        ],
                        [
                            120.69283631700011,
                            31.325836086000038
                        ],
                        [
                            120.69164086800004,
                            31.32669110100005
                        ],
                        [
                            120.68863215100009,
                            31.326801286000034
                        ],
                        [
                            120.68702033200009,
                            31.326473974000066
                        ],
                        [
                            120.68635741800006,
                            31.326669202000062
                        ]
                    ]
                    ,[
                        [
                            120.693816835,
                            31.305258158000072
                        ],
                        [
                            120.69491047800011,
                            31.30626960400008
                        ],
                        [
                            120.69654214200011,
                            31.30698462400005
                        ],
                        [
                            120.69750430500005,
                            31.30673235900008
                        ],
                        [
                            120.69899532200009,
                            31.305165637000073
                        ],
                        [
                            120.69860932600011,
                            31.30412089600003
                        ],
                        [
                            120.69663050200006,
                            31.30403247600003
                        ],
                        [
                            120.69573029300011,
                            31.30446787900007
                        ],
                        [
                            120.69438126800003,
                            31.30400006700006
                        ],
                        [
                            120.69357564400002,
                            31.30448497900005
                        ],
                        [
                            120.693816835,
                            31.305258158000072
                        ]
                    ]
                    ,[
                        [
                            120.69987567600003,
                            31.312030635000042
                        ],
                        [
                            120.69967663700004,
                            31.31248064500005
                        ],
                        [
                            120.70003826700008,
                            31.312898012000062
                        ],
                        [
                            120.69995806100007,
                            31.313873839000053
                        ],
                        [
                            120.70061791100011,
                            31.314393524000025
                        ],
                        [
                            120.70139979500004,
                            31.313788523000028
                        ],
                        [
                            120.70332533600003,
                            31.313121006000074
                        ],
                        [
                            120.70408087200008,
                            31.313494023000032
                        ],
                        [
                            120.70476220500007,
                            31.31232934800005
                        ],
                        [
                            120.70382280600006,
                            31.311930579000034
                        ],
                        [
                            120.70394860100009,
                            31.310698226000056
                        ],
                        [
                            120.703468369,
                            31.309955729000023
                        ],
                        [
                            120.70281537400001,
                            31.309652510000035
                        ],
                        [
                            120.70247532200005,
                            31.309684395000033
                        ],
                        [
                            120.70185128000003,
                            31.310470202000033
                        ],
                        [
                            120.70247650800002,
                            31.310619563000046
                        ],
                        [
                            120.7024192240001,
                            31.311009693000074
                        ],
                        [
                            120.70333000500011,
                            31.311632286000076
                        ],
                        [
                            120.70281719800005,
                            31.312124307000033
                        ],
                        [
                            120.70298094000009,
                            31.312843428000065
                        ],
                        [
                            120.70089796700006,
                            31.31257309800003
                        ],
                        [
                            120.70070241600001,
                            31.311607106000054
                        ],
                        [
                            120.69987567600003,
                            31.312030635000042
                        ]
                    ]
                ]
            },
            "properties": {
                id: "9999"
            }
        }
    ]
};

**Comment by nicoptere** [comment]
yes, it is not a bug :)

this is because the triangulation step doesn't handle geometries with holes.
in the features properties, you have 3 polylines, and in my script, I handle only one of them.
you can change the code so that it handles multiple polylines the triangulation lib I use is [https://www.npmjs.com/package/cdt2d](https://www.npmjs.com/package/cdt2d) feel free to make the changes so that it suits your needs.
